repos:
  - repo: local
    hooks:
      - id: conway
        name: conway
        entry: verilator --timescale 10ns/1ns --clk --assert -Wall --trace --binary cores/conway/tests/conway_tb.sv cores/conway/src/conway.sv
        language: system
        always_run: true
        pass_filenames: false
