name: Simulate riscy chips

on:
  push:
    branches:
      - '**'

jobs:
  riscy32_single:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        component: ["alu", "memory", "register", "control"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@v0.0.2

    - name: Run the testbench
      run: | 
        verilator --timescale 10ns/1ns --clk --assert -Wall --trace --binary cores/riscy32_single/tests/${{ matrix.component }}_tb.sv cores/riscy32_single/src/${{ matrix.component }}.sv;
        ./obj_dir/V${{ matrix.component }}_tb

      #    - name: Run CPU testbench
      #      if: success()
      #      run: | 
      #        verilator --timescale 10ns/1ns --clk --assert -Wall --trace --binary cores/riscy32_single/tests/cpu_tb.sv cores/riscy32_single/src/cpu.sv;
      #        ./obj_dir/Vcpu_tb


  conway:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@v0.0.2

    - name: run the testbench
      run: | 
        verilator --timescale 10ns/1ns --clk --assert -Wall --trace --binary cores/conway/tests/conway_tb.sv cores/conway/src/conway.sv;
        ./obj_dir/Vconway_tb

