name: Simulate riscy chips

on:
  push:
    branches:
      - '**'

jobs:
  build_verilator:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Verilator Action
      uses: V0XNIHILI/install-verilator-action@main

    - name: Upload Verilator Binary
      uses: actions/upload-artifact@v4
      with:
        name: verilator-binary
        path: /usr/local/share/verilator/

  riscy32_single:
    runs-on: ubuntu-latest
    needs: build_verilator
    strategy:
      matrix: 
        component: ["alu", "memory", "register", "control"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Verilator Binary
      uses: actions/download-artifact@v4
      with:
        name: verilator-binary
        path: ./verilator

    - name: Install dependencies
      run: sudo apt-get install ccache perl python3

    - name: Set up verilator
      run: | 
        sudo mkdir -p /usr/local/share/verilator/
        sudo chown -R $(whoami):$(whoami) /usr/local/share/verilator/ ./verilator
        cp -r ./verilator/* /usr/local/share/verilator/
        chmod -R +x /usr/local/share/verilator/*
        sudo ln -s /usr/local/share/verilator/bin/verilator /usr/local/bin/verilator

    - name: Run the testbench
      run: | 
        verilator --timescale 10ns/1ns --clk --assert -Wall --trace --binary cores/riscy32_single/tests/${{ matrix.component }}_tb.sv cores/riscy32_single/src/${{ matrix.component }}.sv;
        ./obj_dir/V${{ matrix.component }}_tb

  conway:
    runs-on: ubuntu-latest
    needs: build_verilator

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Verilator Binary
      uses: actions/download-artifact@v4
      with:
        name: verilator-binary
        path: ./verilator

    - name: Install dependencies
      run: sudo apt-get install ccache perl python3

    - name: Set up verilator
      run: | 
        sudo mkdir -p /usr/local/share/verilator/
        sudo chown -R $(whoami):$(whoami) /usr/local/share/verilator/ ./verilator 
        cp -r ./verilator/* /usr/local/share/verilator/
        chmod -R +x /usr/local/share/verilator/*
        sudo ln -s /usr/local/share/verilator/bin/verilator /usr/local/bin/verilator

    - name: Run the testbench
      run: | 
        verilator --timescale 10ns/1ns --clk --assert -Wall --trace --binary cores/conway/tests/conway_tb.sv cores/conway/src/conway.sv;
        ./obj_dir/Vconway_tb
